# Generated by Django 4.2 on 2023-04-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
            bases=('core.base',),
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.base')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='audio/%Y/%m/%d')),
                ('avaliacao', models.IntegerField(default=0)),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimento_audios', to='core.experimento')),
            ],
            bases=('core.base',),
        ),
    ]
