# Generated by Django 4.2 on 2023-04-20 17:49

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('arquivo', models.FileField(upload_to='audio/%Y/%m/%d', validators=[core.models.MaxSizeValidator(10485760), core.models.ExtensionValidator(['wav'])])),
                ('criterio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experimento_audios', to='core.experimento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
