# Generated by Django 4.2 on 2023-04-20 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='arquivo',
            new_name='archive',
        ),
        migrations.RenameField(
            model_name='audio',
            old_name='criterio',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='experimento',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='experimento',
            old_name='nome',
            new_name='name',
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('score', models.IntegerField()),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_evaluations', to='core.audio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_evaluations', to='core.usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
