# Generated by Django 4.2 on 2023-04-18 16:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='arquivo',
            field=models.FileField(default=1, upload_to='audio/%Y/%m/%d', validators=[core.models.MaxSizeValidator(10485760), core.models.ExtensionValidator(['wav'])]),
            preserve_default=False,
        ),
    ]
