# Generated by Django 4.2 on 2023-04-28 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_audio_row_alter_row_row'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='category',
            new_name='form',
        ),
    ]
