# Generated by Django 4.2 on 2023-04-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_category_audio_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='row',
            field=models.CharField(max_length=10),
        ),
    ]
