# Generated by Django 4.2 on 2023-05-03 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_row_row'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='category',
        ),
        migrations.AddField(
            model_name='audio',
            name='referencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='form',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='form_evaluations', to='core.experimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='score',
            field=models.CharField(max_length=100),
        ),
    ]
